FinalProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('application.urls')),
    path('', include('django.contrib.auth.urls')),
    path('', include('dashboard.urls')),
    path('', include('classification.urls')),



]

dashboard/urls.py
from django.urls import path
from .views import (
    DASHBOARD,
    PROFILE,
    HISTORY,
    Feedback_Done,
    CHANGEPASSWORD,
    detailed,
    FEEDBACK,
    DeleteGroup,
    UPDATTEXT,
    UpdateGroup,
)

urlpatterns = [
    path("dashboard", DASHBOARD.as_view(), name="dashboard"),
    path("profile", PROFILE.as_view(), name="profile"),
    path("history", HISTORY.as_view(), name="history"),
    path("feedback", FEEDBACK.as_view(), name="feedback"),
    path("feedback_done", Feedback_Done.as_view(), name="feedback_done"),
    path("changepassword", CHANGEPASSWORD.as_view(), name="changepassword"),
    path("details/<str:group>/", detailed.as_view(), name="details"),
    path('history/<str:group>/update/', UpdateGroup.as_view(), name='update_group'),
    
    path('history/<str:group>/delete/', DeleteGroup.as_view(), name='delete_group'),
    path("updatetext<int:pk>", UPDATTEXT.as_view(), name="updatetext"),
]

dashboard/models.py
from django.db import models


# Create your models here.
class RECORD(models.Model):
    # User, Requirement, Result, date
    title = models.CharField(max_length=255)
    content = models.TextField()
    date = models.DateField(auto_now_add=True)
    user = models.ForeignKey("auth.user", on_delete=models.CASCADE, null=True)
    prediction = models.CharField(max_length=255, default="Unknown")
    group = models.CharField(max_length=100,default="Unknown")


    def __str__(self):
        return self.title


class Feedback(models.Model):
    user = models.ForeignKey("auth.user", on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    feedback = models.TextField()

    def __str__(self):
        return self.feedback

classification/forms.py
from django import forms


class UserInputForm(forms.Form):
    user_statement = forms.CharField(
        widget=forms.Textarea(attrs={'placeholder': 'Enter your description'}),

    )

    group = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Group your statements under a title'}),

    )

    def clean_user_statement(self):
        user_statement = self.cleaned_data['user_statement']
        statements = [s.strip()
                      for s in user_statement.split(';') if s.strip()]

        for statement in statements:
            if len(statement) < 15:  # Checking for 15 characters
                raise forms.ValidationError(
                    "Each statement must be at least 15 characters long.")

        return user_statement

dashboard/views.py
from django.shortcuts import render
from django.views.generic import (
    TemplateView,
    DetailView,
    ListView,
    UpdateView,
    DeleteView,
    CreateView,
)
from .models import RECORD, Feedback
from django.shortcuts import get_object_or_404, redirect
from django.views import View

from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.mixins import LoginRequiredMixin
from django import forms

# Create your views here.


class DASHBOARD(LoginRequiredMixin, TemplateView):
    template_name = "dashboard/userInput.html"


class PROFILE(LoginRequiredMixin, TemplateView):
    template_name = "dashboard/profile.html"


class FEEDBACK(LoginRequiredMixin, CreateView):
    model = Feedback
    template_name = "dashboard/feedback.html"
    fields = ["feedback"]
    success_url = "feedback_done"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class Feedback_Done(LoginRequiredMixin, TemplateView):
    template_name = "dashboard/feedback_done.html"


class HISTORY(LoginRequiredMixin, ListView):
    template_name = "dashboard/history.html"
    model = RECORD
    context_object_name = "groups"

    def get_queryset(self):
        return RECORD.objects.values('group').distinct()


class detailed(LoginRequiredMixin, ListView):
    template_name = "dashboard/detailView.html"
    model = RECORD
    context_object_name = "records"

    def get_queryset(self):
        group = self.kwargs['group']
        return RECORD.objects.filter(group=group)

class DeleteGroup(LoginRequiredMixin, View):
    def post(self, request, group):
        RECORD.objects.filter(group=group).delete()
        return redirect('history')  # Replace 'history' with your history view name


class UpdateGroupForm(forms.Form):
    new_group = forms.CharField(max_length=100, required=True, label='New Group Name')

class UpdateGroup(LoginRequiredMixin, View):
    template_name = 'dashboard/update.html'

    def get(self, request, group):
        form = UpdateGroupForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request, group):
        form = UpdateGroupForm(request.POST)
        if form.is_valid():
            new_group = form.cleaned_data['new_group']
            RECORD.objects.filter(group=group).update(group=new_group)
            return redirect('history')  # Replace 'history' with your history view name
        return render(request, self.template_name, {'form': form})

class CHANGEPASSWORD(LoginRequiredMixin, PasswordChangeView):
    template_name = "dashboard/changepassword.html"
    success_url = reverse_lazy("dashboard")


class UPDATTEXT(LoginRequiredMixin, UpdateView):
    model = RECORD
    template_name = "dashboard/update.html"
    fields = ["title"]
    success_url = reverse_lazy("history")


class DELETETEXT(DeleteView):
    login_url = reverse_lazy("login")
    model = RECORD
    template_name = "dashboard/delete.html"
    success_url = reverse_lazy("history")
    context_object_name = "deletetext"

templates/dashboard/changepassword.html
{% load static %}
<!doctype html>
<html class="h-100" lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
    <meta name="description" content="A well made and handcrafted Bootstrap 5 template">
    <link rel="apple-touch-icon" sizes="180x180" href="img/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/favicon-16x16.png">
    <link rel="icon" type="image/png" sizes="96x96" href="img/favicon.png">
    <meta name="author" content="Holger Koenemann">
    <meta name="generator" content="Eleventy v2.0.0">
    <meta name="HandheldFriendly" content="true">
    <title>AI-POWERED SPRC</title>
    <link rel="stylesheet" href="{% static 'css/theme.min.css' %}">


    {% include 'fonts.html' %}



    <style>
        .main_profile_div {
            background-color: #111;
            width: 100%;
            height: 100vh;
            font-size: 14px;
        }

        .main_profile_div h2 {
            font-size: 18px;
        }

        .main_profile_div .inner {
            display: flex;
            justify-content: space-between;
            height: 100vh;

        }

        .left {
            padding: 30px;
            width: 23%;
        }

        .right {
            padding: 20px;
            background-color: #202020;
            width: 78%;
        }

        .left .links {
            height: 80vh;

            display: flex;
            flex-direction: column;
            justify-content: space-between;
        }

        .left .links .upper_links {
            margin-top: 50px;
            display: flex;
            flex-direction: column;
            gap: 20px;
        }

        .left .links a {
            text-decoration: none;
            color: #8A8A8E;
            ;
        }

        .left .links .lower_links {
            display: flex;
            flex-direction: column;
            gap: 20px;
        }

        .right .content {
            padding: 50px;
        }

        .main_profile_div .upper_content_div {
            padding: 20px;
            border-bottom: 1px solid rgba(143, 143, 143, 0.641);
        }

        .main_profile_div .upper_content_div p {
            margin: 20px 0px;
        }

        .btn {
            color: #fff;
        }
    </style>
</head>

<body class="bg-black text-white mt-0" data-bs-spy="scroll" data-bs-target="#navScroll">


    <div class="main_profile_div">
        <div class="inner">
            {% include 'sidebar.html' %}
            <div class="right">
                <div class="content">
                    <div class="upper_content_div">
                        <h2>
                            Change Password
                        </h2>


                    </div>
                    <form method="post" class="custom_login_form">
                        {% csrf_token  %}
                       


    

                            <div class="">
                                <label for="{{form.old_password.id_for_lable}}">Old Password</label>
                                <div> {{ form.old_password }} </div>
                                <div> {{ form.old_password.errors }} </div>
                            </div>
                            <div class="">
                                <label for="{{form.new_password1.id_for_lable}}">New Password</label>
                                <div> {{ form.new_password1 }} </div>
                                <div> {{ form.new_password1.errors }} </div>
                            </div>
                            <div class="">
                                <label for="{{form.new_password2.id_for_lable}}">Confirm Password</label>
                                <div> {{ form.new_password2 }} </div>
                                <div> {{ form.new_password2.errors }} </div>
                            </div>
                            <br>
                            <button type="submit">Change Password</button>

                    </form>
                </div>
            </div>
        </div>
    </div>


    <!-- 
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/aos.js' %}"></script>
    <script>
        AOS.init({
            duration: 800, // values from 0 to 3000, with step 50ms
        }); -->
    // </script>
    // <script>
        //     let scrollpos = window.scrollY
        //     const header = document.querySelector(".navbar")
        //     const header_height = header.offsetHeight

        //     const add_class_on_scroll = () => header.classList.add("scrolled", "shadow-sm")
        //     const remove_class_on_scroll = () => header.classList.remove("scrolled", "shadow-sm")

        //     window.addEventListener('scroll', function () {
        //         scrollpos = window.scrollY;

        //         if (scrollpos >= header_height) {
        //             add_class_on_scroll()
        //         } else {
        //             remove_class_on_scroll()
        //         }

        //         console.log(scrollpos)
        //     })
        // 
    </script>

</body>

</html>

templates/dashboard/delete.html
{% load static %}
<!doctype html>
<html class="h-100" lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
    <meta name="description" content="A well made and handcrafted Bootstrap 5 template">
    <link rel="apple-touch-icon" sizes="180x180" href="img/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/favicon-16x16.png">
    <link rel="icon" type="image/png" sizes="96x96" href="img/favicon.png">
    <meta name="author" content="Holger Koenemann">
    <meta name="generator" content="Eleventy v2.0.0">
    <meta name="HandheldFriendly" content="true">
    <title>AI-Powered-SPRC</title>
    <link rel="stylesheet" href="{% static 'css/theme.min.css' %}">


    {% include 'fonts.html' %}



    <style>
        .main_profile_div {
            background-color: #111;
            width: 100%;
            height: 100vh;
            font-size: 14px;
        }

        .main_profile_div h2 {
            font-size: 18px;
        }

        .main_profile_div .inner {
            display: flex;
            justify-content: space-between;
            height: 100vh;

        }

        .left {
            padding: 30px;
            width: 23%;
        }

        .right {
            padding: 20px;
            background-color: #202020;
            width: 78%;
        }

        .left .links {
            height: 80vh;

            display: flex;
            flex-direction: column;
            justify-content: space-between;
        }

        .left .links .upper_links {
            margin-top: 50px;
            display: flex;
            flex-direction: column;
            gap: 20px;
        }

        .left .links a {
            text-decoration: none;
            color: #8A8A8E;
            ;
        }

        .left .links .lower_links {
            display: flex;
            flex-direction: column;
            gap: 20px;
        }

        .right .content {
            padding: 50px;
        }

        .main_profile_div .upper_content_div {
            padding: 20px;
            border-bottom: 1px solid rgba(143, 143, 143, 0.641);
        }

        .main_profile_div .upper_content_div p {
            margin: 20px 0px;
        }
    </style>
</head>

<body class="bg-black text-white mt-0" data-bs-spy="scroll" data-bs-target="#navScroll">


    <div class="main_profile_div">
        <div class="inner">
            {% include 'sidebar.html' %}
            <div class="right">
                <div class="content">
                    <div class="upper_content_div">
                        <form method="post">
                            {%csrf_token%}
                            <p>ARE YOU SURE YOU WANT TO DELETE? {{details.title}}</p>
                            <input class="btn btn-outline-light" type="submit" value="SURE">
                        </form>
                        <p>

                            <ol>
                                {% for i in records  %}


                                <li class="list_record">
                                    <a class="link-fancy link-fancy-light" style="color: #e7e7e7;"
                                        href="{% url 'record_details' i.pk %}">

                                        {{ i.title }}
                                    </a>
                                    <span class="dots">
                                        ...
                                    </span>

                                    <div class="dots_inner">
                                        <a href="{% url 'updatetext' i.pk %}">Rename</a>
                                        <a href="{% url 'deletetext' i.pk %}" class="dlt">Delete</a>
                                    </div>
                                </li>
                                {% endfor %}

                            </ol>
                        </p>
                    </div>

                </div>

            </div>
        </div>
    </div>

</body>

</html

templates/dashboard/detailView.html
{% load static %}
<!doctype html>
<html class="h-100" lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
    <meta name="description" content="A well made and handcrafted Bootstrap 5 template">
    <link rel="apple-touch-icon" sizes="180x180" href="img/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/favicon-16x16.png">
    <link rel="icon" type="image/png" sizes="96x96" href="img/favicon.png">
    <meta name="author" content="Holger Koenemann">
    <meta name="generator" content="Eleventy v2.0.0">
    <meta name="HandheldFriendly" content="true">
    <title>AI-POWERED-SPRC</title>
    <link rel="stylesheet" href="{% static 'css/theme.min.css' %}">


    {% include 'fonts.html' %}



    <style>
        .main_profile_div {
            background-color: #111;
            width: 100%;
            height: 100vh;
            font-size: 14px;
        }

        .main_profile_div h2 {
            font-size: 18px;
        }

        .main_profile_div .inner {
            display: flex;
            justify-content: space-between;
            min-height: 100vh;

        }

        .left {
            padding: 30px;
            width: 23%;
        }

        .right {
            padding: 20px;
            background-color: #202020;
            width: 78%;
        }

        .left .links {
            height: 80vh;

            display: flex;
            flex-direction: column;
            justify-content: space-between;
        }

        .left .links .upper_links {
            margin-top: 50px;
            display: flex;
            flex-direction: column;
            gap: 20px;
        }

        .left .links a {
            text-decoration: none;
            color: #8A8A8E;
            ;
        }

        .left .links .lower_links {
            display: flex;
            flex-direction: column;
            gap: 20px;
        }

        .right .content {
            padding: 50px;
        }

        .main_profile_div .upper_content_div {
            padding: 20px;
            border-bottom: 1px solid rgba(143, 143, 143, 0.641);
        }

        .main_profile_div .upper_content_div p {
            margin: 20px 0px;
        }

        .btn {
            color: #fff;
        }
    </style>
</head>

<body class="bg-black text-white mt-0" data-bs-spy="scroll" data-bs-target="#navScroll">


    <div class="main_profile_div">
        <div class="inner">
            {% include 'sidebar.html' %}
            <div class="right">
                <div class="content">


                    <div class="records">
                        {% for record in records %}
                        <div style="margin:40px 0px;">
                            
                            <h3 style="font-size: 22px;">
                                Requirement
                            </h3>
                            <br>


                            <div id="content">
                             <strong>Statement</strong> :  {{ record.content }} <br> <br>
                            </div>
    
                            <p>
                                <strong>Prediction</strong> :   {{ record.prediction }}
                            </p>
                            <p>
                              <strong>Date</strong> :   {{ record.date }}
    
                            </p>

                        </div>
                    {% endfor %}

                      

                    </div>



                </div>
            </div>
        </div>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var contentElement = document.getElementById('content');

            // Replace periods, "functional," and "non-functional" with the same plus a line break
            contentElement.innerHTML = contentElement.innerHTML.replace(/\./g, '.<br>').replace(/functional/g,
                'functional<br>').replace(/non-functional/g, 'non-functional<br>');
        });
    </script>

</body>

</html>

templates/dashboard/feedback.html
{% load static %}
<!doctype html>
<html class="h-100" lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
    <meta name="description" content="A well made and handcrafted Bootstrap 5 template">
    <link rel="apple-touch-icon" sizes="180x180" href="img/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/favicon-16x16.png">
    <link rel="icon" type="image/png" sizes="96x96" href="img/favicon.png">
    <meta name="author" content="Holger Koenemann">
    <meta name="generator" content="Eleventy v2.0.0">
    <meta name="HandheldFriendly" content="true">
    <title>AI-POWERED SPRC</title>
    <link rel="stylesheet" href="{% static 'css/theme.min.css' %}">


    {% include 'fonts.html' %}



    <style>
        .main_profile_div {
            background-color: #111;
            width: 100%;
            height: 100vh;
            font-size: 14px;
        }

        .main_profile_div h2 {
            font-size: 18px;
        }

        .main_profile_div .inner {
            display: flex;
            justify-content: space-between;
            height: 100vh;

        }

        .left {
            padding: 30px;
            width: 23%;
        }

        .right {
            padding: 20px;
            background-color: #202020;
            width: 78%;
        }

        .left .links {
            height: 80vh;

            display: flex;
            flex-direction: column;
            justify-content: space-between;
        }

        .left .links .upper_links {
            margin-top: 50px;
            display: flex;
            flex-direction: column;
            gap: 20px;
        }

        .left .links a {
            text-decoration: none;
            color: #8A8A8E;
            ;
        }

        .left .links .lower_links {
            display: flex;
            flex-direction: column;
            gap: 20px;
        }

        .right .content {
            padding: 50px;
        }

        .main_profile_div .upper_content_div {
            padding: 20px;
            border-bottom: 1px solid rgba(143, 143, 143, 0.641);
        }

        .main_profile_div .upper_content_div p {
            margin: 20px 0px;
        }

        .btn {
            color: #fff;
        }

        .text {

            height: 100px;
            text-align: center;
        }

        .text textarea {
            background: transparent;
            border: 1px solid #918a8a;
            color: #fff;
            outline: none;
            border-radius: 10px;
            height: 130px;
            font-size: 20px;
            padding: 6px 0px;

        }

        .text a {
            margin: 5px;
            border-radius: 10px;
        }
    </style>
</head>

<body class="bg-black text-white mt-0" data-bs-spy="scroll" data-bs-target="#navScroll">


    <div class="main_profile_div">
        <div class="inner">
            {% include 'sidebar.html' %}
            <div class="right">
                <div class="content">
                    <div class="right">
                        <div class="content">
                            <div class="upper_content_div">
                                <h2>
                                    Give Us a Feedback
                                </h2>


                                <p>
                                    Your valuable feedback means alot for our app to improve it.
                                </p>
                            </div>
                        </div>
                        <form class="text" method="post">
                            {% csrf_token %}
                            {{ form.feedback }}
                            <br>
                            <button type="submit" class="btn btn-outline-light"> submit</button>


                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>




</body>

</html>

templates/dashboard/main.html
{% load static %}
<!doctype html>
<html class="h-100" lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
    <meta name="description" content="A well made and handcrafted Bootstrap 5 template">
    <link rel="apple-touch-icon" sizes="180x180" href="img/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/favicon-16x16.png">
    <link rel="icon" type="image/png" sizes="96x96" href="img/favicon.png">
    <meta name="author" content="Holger Koenemann">
    <meta name="generator" content="Eleventy v2.0.0">
    <meta name="HandheldFriendly" content="true">
    <title>AI AI-Powered-SPRC</title>
    <link rel="stylesheet" href="{% static 'css/theme.min.css' %}">


    {% include 'fonts.html' %}


    <style>
        .main_profile_div {
            background-color: #111;
            width: 100%;
            height: 100vh;
            font-size: 14px;
        }

        .main_profile_div h2 {
            font-size: 18px;
        }

        .main_profile_div .inner {
            display: flex;
            justify-content: space-between;
            min-height: 100vh;

        }

        .left {
            padding: 30px;
            width: 23%;
        }

        .right {
            padding: 20px;
            background-color: #202020;
            width: 78%;
        }

        .left .links {
            height: 80vh;

            display: flex;
            flex-direction: column;
            justify-content: space-between;
        }

        .left .links .upper_links {
            margin-top: 50px;
            display: flex;
            flex-direction: column;
            gap: 20px;
        }

        .left .links a {
            text-decoration: none;
            color: #8A8A8E;
            ;
        }

        .left .links button {
            border: none;
            outline: none;
            text-decoration: none;
            color: #8A8A8E;
            padding: 0px;
            background-color: transparent;
        }

        .left .links .lower_links {
            display: flex;
            flex-direction: column;
            gap: 20px;
        }

        .right .content {
            padding: 50px;
        }

        .main_profile_div .upper_content_div {
            padding: 20px;
            border-bottom: 1px solid rgba(143, 143, 143, 0.641);
        }

        .main_profile_div .upper_content_div p {
            margin: 20px 0px;
        }

        .text {

            height: 200px;
            text-align: center;
        }

        .text textarea {
            background-color: transparent;
            width: 500px;
            border-radius: 10px;
            padding: 5px 5px;
            font-size: 15px;
            color: #fff;

        }

        .text a {
            margin: 5px;
            border-radius: 10px;
        }
        label[for="id_user_statement"] {
            display: none;
        }

        label[for="id_group"]{
            display:none;
        }
        #id_group {
            background-color: transparent;
            width: 500px;
            border-radius: 10px;
            padding: 5px 5px;
            font-size: 15px;
            color: #fff;
            border: 1px solid #8a8a8a;
        }
    </style>
</head>

<body class="bg-black text-white mt-0" data-bs-spy="scroll" data-bs-target="#navScroll">
    <div class="main_profile_div">
        <div class="inner">
            {% include 'sidebar.html' %}
            <div class="right">
                <div class="content">
                    <div class="upper_content_div description">
                        <h1>Welcome</h1>
                        <h2 class="mt-5" style="color: #8A8A8E; margin-left: 300px;">
                            <strong>How Can I Help You Today?</strong>
                        </h2>
                    </div>
                </div>
                <form method="post" class="text">
                    {% csrf_token %}
                    {{ form.as_p }}
                    {% if form.errors %}
                    <div class="error-messages">
                        <ul>
                            {% for field in form %}
                            {% for error in field.errors %}
                            <li>{{ error }}</li>
                            {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                    {% endif %}
                    <input type="submit" class="btn btn-outline-light" value="Submit">                                                                                                                                                  
                </form>
            </div>
        </div>
    </div>
</body>

</html>

templates/dashboard/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Results</title>
    
</head>
 {% include 'fonts.html' %}

<body>
    
    <style>
        body{
            background-color:black;
            color:white;
            width:100%;
            
        }
        .main{
            
          
          
            display:flex;
            justify-content:center;
            padding:10px 100px;
            
        }
    </style>
   <div class="main">
    <div class="main_inner">
    {% if user_predictions %}
    <h2>Results:</h2>
    <ul>
        {% for statement, prediction in user_predictions %}
            <li>
                <p><strong>Statement:</strong> {{ statement }}</p>
                <p><strong>Prediction:</strong> {{ prediction }}</p>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No predictions available.</p>
{% endif %}
</div>
   </div>
</body>

</html>